version: '3'

services:
    database:
        image: postgres:11-alpine
        restart: always
        container_name: treinamento
        ports:
            - 7778:5432
        environment:
            POSTGRES_DB: treinamento
            POSTGRES_USER: andrey
            POSTGRES_PASSWORD: 123456
